import { Platform, StyleSheet } from 'react-native';

// Screen-scoped tokens translated from the approved Profile mockup.
export const profileColors = {
  ink: '#070b10', panel: '#10161e', raised: '#18212a', cardEnd: '#0f151c',
  gold: '#f6c94a', lightGold: '#ffe59a', paper: '#f5f2e9',
  muted: '#a5abb2', secondary: '#939ca5', danger: '#e3aaa0',
  line: 'rgba(234,230,217,0.105)', goldLine: 'rgba(246,201,74,0.22)',
  goldWash: 'rgba(246,201,74,0.07)', ornament: 'rgba(255,220,126,0.075)',
  overlay: 'rgba(0,0,0,0.75)', ambient: '#1a1915', transparent: 'transparent',
};

export function createProfileStyles(fontsLoaded: boolean) {
  const dm = fontsLoaded ? 'ProfileDM_500' : Platform.OS === 'ios' ? 'System' : 'sans-serif';
  const bold = fontsLoaded ? 'ProfileDM_700' : dm;
  const space = fontsLoaded ? 'ProfileSpace_600' : bold;
  const c = profileColors;
  return StyleSheet.create({
    screen: { flex: 1, backgroundColor: c.ink },
    ambient: { position: 'absolute', top: 0, left: 0, right: 0, height: 360 },
    container: { width: '100%', maxWidth: 430, alignSelf: 'center' },
    status: { position: 'absolute', top: 8, left: 22, right: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    statusTime: { color: c.paper, fontFamily: bold, fontSize: 12 },
    statusIcons: { flexDirection: 'row', gap: 4 },
    header: { height: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20 },
    brand: { flexDirection: 'row', alignItems: 'center', gap: 7 },
    crest: { width: 29, height: 35 },
    wordmark: { width: 116, height: 37 },
    headerLabel: { color: c.muted, fontFamily: bold, fontSize: 9, letterSpacing: 1.25 },
    content: { paddingHorizontal: 20, paddingTop: 9 },
    heading: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginBottom: 13 },
    eyebrow: { color: c.gold, fontFamily: bold, fontSize: 8, letterSpacing: 1.7, marginBottom: 4 },
    title: { color: c.paper, fontFamily: space, fontSize: 24, letterSpacing: -0.8 },
    member: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingVertical: 6, paddingHorizontal: 8, borderWidth: 1, borderColor: c.goldLine, borderRadius: 20, backgroundColor: c.goldWash },
    memberLabel: { color: c.lightGold, fontFamily: bold, fontSize: 7, letterSpacing: 0.8 },
    card: { minHeight: 154, flexDirection: 'row', alignItems: 'center', gap: 16, padding: 17, borderWidth: 1, borderColor: c.goldLine, borderRadius: 16, overflow: 'hidden' },
    ornament: { position: 'absolute', right: -27, bottom: -69, width: 165, height: 165, borderWidth: 1, borderColor: c.ornament, borderRadius: 83 },
    avatarWrap: { width: 82, height: 82, flexShrink: 0 },
    avatar: { width: 82, height: 82, borderWidth: 2, borderColor: c.lightGold, borderRadius: 41, backgroundColor: c.panel, alignItems: 'center', justifyContent: 'center' },
    initials: { color: c.lightGold, fontFamily: space, fontSize: 25 },
    seal: { position: 'absolute', right: -3, bottom: -2, width: 25, height: 25, borderRadius: 13, backgroundColor: c.gold, borderWidth: 2, borderColor: c.panel, alignItems: 'center', justifyContent: 'center' },
    identity: { flex: 1, minWidth: 0 },
    kicker: { color: c.lightGold, fontFamily: bold, fontSize: 7, letterSpacing: 1.25, marginBottom: 5 },
    name: { color: c.paper, fontFamily: space, fontSize: 22, letterSpacing: -0.75 },
    email: { color: c.secondary, fontFamily: dm, fontSize: 10, marginTop: 5 },
    stats: { flexDirection: 'row', marginTop: 11, marginBottom: 16, paddingVertical: 13, borderWidth: 1, borderColor: c.line, borderRadius: 13, backgroundColor: c.panel },
    stat: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
    statDivider: { borderRightWidth: 1, borderRightColor: c.line },
    number: { color: c.lightGold, fontFamily: space, fontSize: 20 },
    statLabel: { color: c.muted, fontFamily: bold, fontSize: 8, letterSpacing: 0.4, textAlign: 'center' },
    sectionHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginHorizontal: 2, marginBottom: 7 },
    sectionTitle: { color: c.paper, fontFamily: space, fontSize: 10, letterSpacing: 1 },
    sectionAside: { color: c.secondary, fontFamily: bold, fontSize: 8, letterSpacing: 0.7 },
    group: { borderWidth: 1, borderColor: c.line, borderRadius: 13, backgroundColor: c.panel, overflow: 'hidden', marginBottom: 13 },
    row: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 12, minHeight: 48 },
    rowBorder: { borderBottomWidth: 1, borderBottomColor: c.line },
    rowPressed: { backgroundColor: c.goldWash },
    rowIcon: { width: 29, height: 29, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.goldLine, borderRadius: 9, backgroundColor: c.goldWash },
    quietIcon: { backgroundColor: c.transparent, borderColor: c.line },
    rowCopy: { flex: 1, minWidth: 0 },
    rowTitle: { color: c.paper, fontFamily: bold, fontSize: 11 },
    rowSubtitle: { color: c.secondary, fontFamily: dm, fontSize: 8, marginTop: 2 },
    danger: { color: c.danger },
    coming: { paddingVertical: 4, paddingHorizontal: 6, borderWidth: 1, borderColor: c.goldLine, borderRadius: 5, backgroundColor: c.goldWash },
    comingLabel: { color: c.lightGold, fontFamily: bold, fontSize: 6, letterSpacing: 0.55 },
    footnote: { color: c.secondary, fontFamily: dm, fontSize: 8, textAlign: 'center', marginVertical: 7 },
    signOut: { alignSelf: 'center', minHeight: 44, justifyContent: 'center', paddingHorizontal: 20 },
    signOutLabel: { color: c.muted, fontFamily: bold, fontSize: 11 },
    errorBox: { borderWidth: 1, borderColor: c.line, borderRadius: 12, padding: 12, marginBottom: 12, marginTop: 8, gap: 7 },
    error: { color: c.danger, fontFamily: dm, fontSize: 12, lineHeight: 18 },
    retry: { minHeight: 44, justifyContent: 'center', alignSelf: 'flex-start' },
    retryLabel: { color: c.gold, fontFamily: bold, fontSize: 12 },
    overlay: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: c.overlay },
    sheet: { width: '100%', maxWidth: 430, alignSelf: 'center', maxHeight: '90%', borderWidth: 1, borderColor: c.line, borderRadius: 20, backgroundColor: c.panel },
    sheetContent: { padding: 20, gap: 14 },
    sheetHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
    sheetTitle: { flex: 1, color: c.paper, fontFamily: space, fontSize: 22 },
    close: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
    body: { color: c.muted, fontFamily: dm, fontSize: 13, lineHeight: 21 },
    fieldLabel: { color: c.paper, fontFamily: bold, fontSize: 12, marginBottom: 7 },
    input: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 12, borderWidth: 1, borderColor: c.line, borderRadius: 10, backgroundColor: c.ink, color: c.paper, fontFamily: dm, fontSize: 15 },
    action: { minHeight: 48, padding: 12, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: c.gold },
    actionLabel: { color: c.ink, fontFamily: bold, fontSize: 13, textAlign: 'center' },
    quietAction: { backgroundColor: c.transparent, borderWidth: 1, borderColor: c.line },
    quietActionLabel: { color: c.paper },
    dangerAction: { backgroundColor: c.goldWash, borderWidth: 1, borderColor: c.danger },
    disabled: { opacity: 0.5 },
  });
}

export type ProfileStyles = ReturnType<typeof createProfileStyles>;
