import { StyleSheet } from 'react-native';
import home from '@/constants/homeColors';

export const passportStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: home.background },
  container: { width: '100%', maxWidth: 480, alignSelf: 'center' },
  header: { minHeight: 49, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, borderBottomWidth: 1, borderBottomColor: 'rgba(239,231,210,0.045)' },
  brand: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 1 },
  crest: { width: 25, height: 31 },
  wordmark: { width: 83, height: 31 },
  brandDivider: { height: 23, width: 1, marginHorizontal: 3, backgroundColor: 'rgba(255,209,46,0.4)' },
  brandLabel: { color: '#e9ddbb', fontFamily: 'Inter_700Bold', fontSize: 8, lineHeight: 11, letterSpacing: 0.85 },
  mapButton: { minHeight: 44, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 8, borderWidth: 1, borderColor: 'rgba(255,209,46,0.3)', backgroundColor: 'rgba(255,209,46,0.055)' },
  mapButtonText: { color: '#f2d882', fontFamily: 'Inter_700Bold', fontSize: 11 },
  content: { paddingHorizontal: 18, paddingTop: 12 },
  sectionCopy: { flex: 1 },
  intro: { minHeight: 53, marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 9 },
  eyebrow: { color: '#c4b991', fontFamily: 'Inter_700Bold', fontSize: 8, letterSpacing: 1, lineHeight: 12 },
  title: { color: home.text, fontFamily: 'Inter_700Bold', fontSize: 21, letterSpacing: -0.6, marginTop: 4 },
  stamp: { width: 43, height: 43, borderRadius: 22, borderWidth: 1, borderColor: '#716334', alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '10deg' }] },
  stampText: { color: '#cbb867', fontFamily: 'Inter_700Bold', fontSize: 8, lineHeight: 10, textAlign: 'center' },
  stats: { minHeight: 68, flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderRadius: 11, borderWidth: 1, borderColor: home.line, backgroundColor: '#0d131b' },
  stat: { flex: 1, alignItems: 'center', paddingHorizontal: 3, gap: 5 },
  statDivider: { borderLeftWidth: 1, borderLeftColor: home.line },
  statValue: { fontFamily: 'Inter_700Bold', color: home.gold, fontSize: 25, lineHeight: 29 },
  statLabel: { fontFamily: 'Inter_600SemiBold', color: '#b5b6b3', fontSize: 7, letterSpacing: 0.8 },
  discovery: { marginTop: 12, minHeight: 127, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,209,46,0.32)', backgroundColor: home.panelSoft },
  discoveryCopy: { flex: 1, gap: 5 },
  goldEyebrow: { color: '#dfc256', fontSize: 7 },
  discoveryTitle: { fontFamily: 'Inter_700Bold', color: home.text, fontSize: 19, letterSpacing: -0.5 },
  discoveryText: { fontFamily: 'Inter_400Regular', color: '#b5b8b5', fontSize: 10, lineHeight: 15 },
  exploreButton: { marginTop: 4, minHeight: 44, paddingHorizontal: 10, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 8, borderRadius: 7, backgroundColor: home.gold },
  exploreText: { fontFamily: 'Inter_700Bold', color: home.actionInk, fontSize: 10 },
  mapArt: { width: '29%', maxWidth: 120, height: 99, overflow: 'hidden', borderRadius: 9, borderWidth: 1, borderColor: '#384447' },
  sectionHeading: { marginTop: 18, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { fontFamily: 'Inter_700Bold', fontSize: 14, color: home.text, marginTop: 4, letterSpacing: -0.2 },
  sectionCount: { flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  count: { fontFamily: 'Inter_700Bold', fontSize: 15, color: home.gold },
  countLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 7, color: home.muted, letterSpacing: 0.5 },
  filters: { flexDirection: 'row', padding: 3, borderRadius: 8, borderWidth: 1, borderColor: home.line, backgroundColor: home.panel },
  filter: { flex: 1, minHeight: 44, borderRadius: 6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  filterSelected: { backgroundColor: home.gold },
  filterLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 11, color: home.muted },
  filterLabelSelected: { color: home.actionInk },
  filterCount: { fontFamily: 'Inter_700Bold', fontSize: 9, color: home.muted },
  list: { marginTop: 8, gap: 8 },
  pubCard: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 7, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(239,231,210,0.09)' },
  photo: { width: 77, height: 80, borderRadius: 7, overflow: 'hidden', backgroundColor: home.panelSoft },
  photoImage: { width: '100%', height: '100%' },
  photoShade: { ...StyleSheet.absoluteFill, top: '35%' },
  photoCaption: { position: 'absolute', bottom: 5, left: 5, fontFamily: 'Inter_700Bold', fontSize: 6, color: '#f3e6bc', letterSpacing: 0.4 },
  pubCopy: { flex: 1, gap: 4 },
  pubName: { fontFamily: 'Inter_600SemiBold', fontSize: 13, color: home.text },
  identification: { fontFamily: 'Inter_500Medium', fontSize: 9, color: '#d5bf70' },
  location: { fontFamily: 'Inter_400Regular', fontSize: 9, lineHeight: 13, color: home.muted },
  pints: { fontFamily: 'Inter_600SemiBold', fontSize: 10, color: '#d5bf70' },
  visit: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  visitText: { flexShrink: 1, fontFamily: 'Inter_400Regular', fontSize: 9, lineHeight: 13, color: home.muted },
  reviewCount: { fontFamily: 'Inter_400Regular', fontSize: 9, color: home.muted },
  reviewBadge: { minWidth: 48, minHeight: 44, paddingHorizontal: 4, paddingVertical: 5, gap: 3, alignItems: 'center', justifyContent: 'center', borderRadius: 6, borderWidth: 1, borderColor: 'rgba(239,231,210,0.14)', backgroundColor: 'rgba(255,255,255,0.035)' },
  reviewBadgeGold: { borderColor: 'rgba(255,209,46,0.2)', backgroundColor: 'rgba(255,209,46,0.055)' },
  rating: { fontFamily: 'Inter_700Bold', fontSize: 10, color: home.gold },
  reviewStatus: { fontFamily: 'Inter_600SemiBold', fontSize: 7, color: home.muted },
  reviewStatusGold: { color: home.gold },
  state: { padding: 20, marginTop: 12, gap: 12, borderRadius: 10, borderWidth: 1, borderColor: home.line, backgroundColor: home.panel },
  stateTitle: { fontFamily: 'Inter_700Bold', fontSize: 16, color: home.text },
  stateText: { fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 19, color: home.muted },
  retry: { minHeight: 44, alignSelf: 'flex-start', justifyContent: 'center' },
  retryText: { fontFamily: 'Inter_700Bold', fontSize: 13, color: home.gold },
  photoNote: { fontFamily: 'Inter_400Regular', fontSize: 9, lineHeight: 14, color: home.muted, marginTop: 10 },
  endNote: { fontFamily: 'Inter_400Regular', fontSize: 10, color: home.muted, fontStyle: 'italic', textAlign: 'center', marginTop: 16 },
  groupingNote: { fontFamily: 'Inter_400Regular', fontSize: 10, lineHeight: 16, color: home.muted, marginTop: 20 },
});
