// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pint-wars-nearby/NearbyPubs.tsx": () => import("../components/mockups/pint-wars-nearby/NearbyPubs.tsx"),
  "./components/mockups/pint-wars-passport/Passport.tsx": () => import("../components/mockups/pint-wars-passport/Passport.tsx"),
  "./components/mockups/pint-wars-profile/Current.tsx": () => import("../components/mockups/pint-wars-profile/Current.tsx"),
  "./components/mockups/pint-wars-profile/Profile.tsx": () => import("../components/mockups/pint-wars-profile/Profile.tsx"),
  "./components/mockups/pint-wars-reference/ActiveWar.tsx": () => import("../components/mockups/pint-wars-reference/ActiveWar.tsx"),
  "./components/mockups/pint-wars-reference/Current.tsx": () => import("../components/mockups/pint-wars-reference/Current.tsx"),
  "./components/mockups/pint-wars-reference/HomeActive.tsx": () => import("../components/mockups/pint-wars-reference/HomeActive.tsx"),
  "./components/mockups/pint-wars-reference/HomeNoActive.tsx": () => import("../components/mockups/pint-wars-reference/HomeNoActive.tsx"),
  "./components/mockups/pint-wars-reference/Wars.tsx": () => import("../components/mockups/pint-wars-reference/Wars.tsx"),
  "./components/mockups/pint-wars/WarRoom.tsx": () => import("../components/mockups/pint-wars/WarRoom.tsx")
};
