import { StyleSheet } from 'react-native';
import home from '@/constants/homeColors';

export const activeWarColors = {
  ...home,
  panel: '#0e1319',
  paper: '#f4f2ec',
  secondary: '#afb4bc',
  wash: '#ffe895',
  rule: 'rgba(235,231,216,0.105)',
  shade: 'rgba(5,8,13,0.84)',
  avatar: ['#a48b59', '#4b625d', '#595466', '#705044', '#41606e'],
};

export function createActiveWarStyles(loaded: boolean, compact = false) {
  const c = activeWarColors;
  const medium = loaded ? 'WarsDM_500' : 'Inter_500Medium';
  const bold = loaded ? 'WarsDM_700' : 'Inter_700Bold';
  const headline = loaded ? 'WarsSpace_600' : 'Inter_600SemiBold';
  return StyleSheet.create({
    scroll: { flex: 1 },
    content: { width: '100%', maxWidth: 430, alignSelf: 'center', paddingHorizontal: 18 },
    status: { position: 'absolute', top: 11, left: 23, right: 23, flexDirection: 'row', justifyContent: 'space-between' },
    statusText: { color: c.paper, fontFamily: bold, fontSize: 12 },
    icons: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    header: { height: 53, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    brand: { flexDirection: 'row', gap: 7, alignItems: 'center' },
    crest: { width: 29, height: 35 },
    wordmark: { width: 119, height: 39 },
    invite: { minHeight: 34, paddingHorizontal: 10, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(255,209,46,0.34)', backgroundColor: 'rgba(255,209,46,0.06)', flexDirection: 'row', alignItems: 'center', gap: 6 },
    inviteText: { color: c.gold, fontFamily: bold, fontSize: 11 },
    back: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 5 },
    backText: { color: c.secondary, fontFamily: bold, fontSize: 9, letterSpacing: 0.75 },
    hero: { minHeight: 121, overflow: 'hidden', borderRadius: 13, borderWidth: 1, borderColor: 'rgba(255,209,46,0.21)', backgroundColor: c.panel, padding: 13 },
    photo: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', opacity: 0.68 },
    heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
    liveBadge: { minHeight: 20, paddingHorizontal: 7, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(255,217,94,0.24)', backgroundColor: 'rgba(8,11,14,0.54)', flexDirection: 'row', alignItems: 'center', gap: 6 },
    dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: c.gold },
    smallGold: { color: c.wash, fontFamily: bold, fontSize: 8, letterSpacing: 0.65 },
    countdown: { flexDirection: 'row', gap: 4, alignItems: 'center', flexShrink: 1 },
    countdownText: { color: c.wash, fontFamily: bold, fontSize: 8, flexShrink: 1 },
    heroTitle: { marginTop: 23, marginBottom: 5, color: c.paper, fontFamily: headline, fontSize: 24, lineHeight: 27, letterSpacing: -0.8 },
    meta: { flexDirection: 'row', alignItems: 'center', gap: 7, flexWrap: 'wrap' },
    metaText: { color: c.paper, fontFamily: bold, fontSize: 8, letterSpacing: 0.4 },
    place: { marginLeft: 'auto', minHeight: 19, paddingHorizontal: 6, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(255,209,46,0.3)', backgroundColor: 'rgba(255,209,46,0.12)', flexDirection: 'row', alignItems: 'center', gap: 4 },
    placeText: { color: c.wash, fontFamily: bold, fontSize: 7 },
    tabs: { marginTop: 11, minHeight: 36, padding: 3, flexDirection: 'row', gap: 3, borderRadius: 10, borderWidth: 1, borderColor: c.rule, backgroundColor: 'rgba(255,255,255,0.033)' },
    tab: { flex: 1, minHeight: 28, borderRadius: 7, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'transparent' },
    selectedTab: { borderColor: 'rgba(255,209,46,0.16)', backgroundColor: 'rgba(255,209,46,0.11)' },
    tabText: { color: c.secondary, fontFamily: bold, fontSize: 10 },
    selectedText: { color: c.paper },
    sectionHeading: { marginTop: 2, marginBottom: 2, minHeight: 40, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    standingPill: { minHeight: 20, paddingHorizontal: 7, borderRadius: 6, borderWidth: 1, borderColor: c.rule, flexDirection: 'row', alignItems: 'center', gap: 5 },
    eyebrow: { color: c.gold, fontFamily: bold, fontSize: 7, letterSpacing: 1.15 },
    heading: { color: c.paper, fontFamily: headline, fontSize: 15, lineHeight: 18 },
    board: { overflow: 'hidden', borderRadius: 12, borderWidth: 1, borderColor: c.rule, backgroundColor: c.panel },
    boardHead: { minHeight: 28, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.rule },
    column: { color: '#777f88', fontFamily: bold, fontSize: 7, letterSpacing: 0.83 },
    rankColumn: { width: 18 },
    playerColumn: { flex: 1 },
    row: { minHeight: compact ? 35 : 41, paddingHorizontal: 10, paddingVertical: compact ? 3 : 5, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.rule },
    yourRow: { backgroundColor: 'rgba(255,209,46,0.085)', borderWidth: 1, borderRadius: 7, borderColor: 'rgba(255,209,46,0.3)' },
    yourMarker: { position: 'absolute', left: 0, top: 4, bottom: 4, width: 2, backgroundColor: c.gold },
    rank: { width: 18, color: '#868d95', fontFamily: headline, fontSize: 9 },
    topRank: { color: '#d8b444' },
    yourRank: { color: c.gold },
    avatar: { width: 27, height: 27, borderRadius: 14, borderWidth: 1, borderColor: c.rule, justifyContent: 'center', alignItems: 'center' },
    avatarText: { color: c.paper, fontFamily: bold, fontSize: 8 },
    yourAvatar: { backgroundColor: c.gold, borderColor: c.gold },
    yourAvatarText: { color: c.actionInk },
    playerCopy: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5 },
    name: { flexShrink: 1, color: c.paper, fontFamily: medium, fontSize: 11 },
    yourName: { color: '#fff4d2', fontFamily: bold },
    tag: { paddingHorizontal: 4, paddingVertical: 2, borderRadius: 3, backgroundColor: c.gold },
    tagText: { color: c.actionInk, fontFamily: bold, fontSize: 6 },
    role: { color: c.secondary, fontFamily: medium, fontSize: 7 },
    score: { color: '#f1d577', fontFamily: headline, fontSize: 12 },
    yourScore: { color: c.gold },
    units: { color: c.secondary, fontFamily: medium, fontSize: 8 },
    log: { minHeight: 44, marginTop: 10, borderWidth: 1, borderColor: 'rgba(255,235,164,0.6)', borderRadius: 10, overflow: 'hidden', flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 12 },
    logIcon: { width: 25, height: 25, borderRadius: 7, borderWidth: 1, borderColor: 'rgba(46,34,6,0.17)', backgroundColor: 'rgba(255,255,255,0.25)', justifyContent: 'center', alignItems: 'center' },
    logCopy: { flex: 1 },
    logTitle: { color: c.actionInk, fontFamily: bold, fontSize: 12 },
    logHint: { color: c.actionInk, fontFamily: medium, fontSize: 8 },
    body: { color: c.secondary, fontFamily: medium, fontSize: 12, lineHeight: 18 },
    panel: { marginTop: 10, padding: 13, borderRadius: 12, borderWidth: 1, borderColor: c.rule, backgroundColor: c.panel, gap: 10 },
    detailRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
    detailCopy: { flex: 1, gap: 3 },
    detailTitle: { color: c.paper, fontFamily: bold, fontSize: 12 },
    management: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 9, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: c.rule },
    link: { color: c.gold, fontFamily: bold, fontSize: 11 },
    nav: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: c.background, borderTopWidth: 1, borderTopColor: c.rule, flexDirection: 'row', paddingHorizontal: 13, paddingTop: 10 },
    navItem: { flex: 1, minHeight: 41, alignItems: 'center', gap: 4 },
    navText: { color: c.secondary, fontFamily: medium, fontSize: 9 },
    selectedNavText: { color: c.gold },
    activity: { marginTop: 13 },
    activityHeader: { minHeight: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    activityTitle: { color: c.paper, fontFamily: headline, fontSize: 8, letterSpacing: 1 },
    activityRow: { minHeight: 41, paddingVertical: 5, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.rule },
    activityCopy: { flex: 1, gap: 2 },
    activityText: { color: c.paper, fontFamily: medium, fontSize: 10, lineHeight: 14 },
    activityName: { fontFamily: bold },
    activityVenue: { color: c.secondary, fontFamily: medium, fontSize: 8 },
    activityTime: { color: c.secondary, fontFamily: medium, fontSize: 7 },
    refresh: { minWidth: 32, minHeight: 28, alignItems: 'center', justifyContent: 'center' },
    viewAll: { minHeight: 32, justifyContent: 'center', alignSelf: 'flex-start' },
  });
}
