import { StyleSheet } from 'react-native';
import home from '@/constants/homeColors';

export const activeWarColors = {
  ...home,
  panel: '#0e1319',
  paper: '#f4f2ec',
  secondary: '#afb4bc',
  wash: '#ffe895',
  rule: 'rgba(235,231,216,0.105)',
  shade: 'rgba(5,8,13,0.84)',
  avatar: ['#dcae35', '#35414a', '#483b52', '#564039', '#34494f'],
};

export function createActiveWarStyles(loaded: boolean) {
  const c = activeWarColors;
  const medium = loaded ? 'WarsDM_500' : 'Inter_500Medium';
  const bold = loaded ? 'WarsDM_700' : 'Inter_700Bold';
  const headline = loaded ? 'WarsSpace_600' : 'Inter_600SemiBold';
  return StyleSheet.create({
    scroll: { flex: 1 },
    content: { width: '100%', maxWidth: 430, alignSelf: 'center', paddingHorizontal: 19 },
    status: { position: 'absolute', top: 11, left: 23, right: 23, flexDirection: 'row', justifyContent: 'space-between' },
    statusText: { color: c.paper, fontFamily: bold, fontSize: 12 },
    icons: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    header: { height: 55, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    brand: { flexDirection: 'row', gap: 7, alignItems: 'center' },
    crest: { width: 31, height: 37 },
    wordmark: { width: 122, height: 41 },
    invite: { minHeight: 36, paddingHorizontal: 11, borderRadius: 10, borderWidth: 1, borderColor: c.rule, backgroundColor: 'rgba(255,209,46,0.06)', flexDirection: 'row', alignItems: 'center', gap: 5 },
    inviteText: { color: c.gold, fontFamily: bold, fontSize: 10 },
    back: { minHeight: 37, flexDirection: 'row', alignItems: 'center', gap: 7 },
    backText: { color: c.secondary, fontFamily: bold, fontSize: 10, letterSpacing: 1 },
    hero: { minHeight: 127, overflow: 'hidden', borderRadius: 13, borderWidth: 1, borderColor: 'rgba(255,209,46,0.25)', backgroundColor: c.panel, padding: 12 },
    photo: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', opacity: 0.66 },
    heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
    liveBadge: { minHeight: 23, paddingHorizontal: 8, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,209,46,0.28)', backgroundColor: 'rgba(8,11,14,0.48)', flexDirection: 'row', alignItems: 'center', gap: 5 },
    dot: { width: 5, height: 5, borderRadius: 3, backgroundColor: c.gold },
    smallGold: { color: c.wash, fontFamily: bold, fontSize: 8, letterSpacing: 0.65 },
    countdown: { flexDirection: 'row', gap: 4, alignItems: 'center', flexShrink: 1 },
    countdownText: { color: c.wash, fontFamily: bold, fontSize: 8, flexShrink: 1 },
    heroTitle: { marginTop: 25, marginBottom: 7, color: c.paper, fontFamily: headline, fontSize: 27, lineHeight: 29, letterSpacing: -0.85 },
    meta: { flexDirection: 'row', alignItems: 'center', gap: 7, flexWrap: 'wrap' },
    metaText: { color: c.paper, fontFamily: bold, fontSize: 8, letterSpacing: 0.4 },
    place: { marginLeft: 'auto', minHeight: 19, paddingHorizontal: 6, borderRadius: 6, borderWidth: 1, borderColor: 'rgba(255,209,46,0.3)', backgroundColor: 'rgba(255,209,46,0.12)', flexDirection: 'row', alignItems: 'center', gap: 4 },
    placeText: { color: c.wash, fontFamily: bold, fontSize: 7 },
    tabs: { marginTop: 9, minHeight: 35, padding: 3, flexDirection: 'row', gap: 3, borderRadius: 10, borderWidth: 1, borderColor: c.rule, backgroundColor: 'rgba(255,255,255,0.035)' },
    tab: { flex: 1, minHeight: 28, borderRadius: 7, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'transparent' },
    selectedTab: { borderColor: 'rgba(255,209,46,0.16)', backgroundColor: 'rgba(255,209,46,0.11)' },
    tabText: { color: c.secondary, fontFamily: bold, fontSize: 9 },
    selectedText: { color: c.wash },
    sectionHeading: { marginTop: 8, marginBottom: 7, minHeight: 28, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    eyebrow: { color: c.gold, fontFamily: bold, fontSize: 7, letterSpacing: 1.15 },
    heading: { color: c.paper, fontFamily: headline, fontSize: 15, lineHeight: 18 },
    board: { overflow: 'hidden', borderRadius: 12, borderWidth: 1, borderColor: c.rule, backgroundColor: c.panel },
    boardHead: { minHeight: 22, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.rule },
    column: { color: c.secondary, fontFamily: bold, fontSize: 6, letterSpacing: 1 },
    rankColumn: { width: 25 },
    playerColumn: { flex: 1 },
    row: { minHeight: 33, paddingHorizontal: 10, paddingVertical: 3, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.rule },
    yourRow: { backgroundColor: 'rgba(255,209,46,0.075)', borderWidth: 1, borderColor: 'rgba(255,209,46,0.39)' },
    yourMarker: { position: 'absolute', left: 0, top: 4, bottom: 4, width: 2, backgroundColor: c.gold },
    rank: { width: 25, color: c.secondary, fontFamily: headline, fontSize: 9 },
    yourRank: { color: c.gold },
    avatar: { width: 25, height: 25, borderRadius: 13, borderWidth: 1, borderColor: c.rule, justifyContent: 'center', alignItems: 'center' },
    avatarText: { color: c.paper, fontFamily: bold, fontSize: 7 },
    yourAvatar: { backgroundColor: c.gold, borderColor: c.gold },
    yourAvatarText: { color: c.actionInk },
    playerCopy: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5 },
    name: { flexShrink: 1, color: c.paper, fontFamily: bold, fontSize: 10 },
    tag: { paddingHorizontal: 4, paddingVertical: 2, borderRadius: 3, backgroundColor: c.gold },
    tagText: { color: c.actionInk, fontFamily: bold, fontSize: 6 },
    role: { color: c.secondary, fontFamily: medium, fontSize: 7 },
    score: { color: c.gold, fontFamily: headline, fontSize: 11 },
    units: { color: c.secondary, fontFamily: medium, fontSize: 8 },
    log: { minHeight: 44, marginTop: 8, borderWidth: 1, borderColor: c.wash, borderRadius: 11, overflow: 'hidden', flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 12 },
    logIcon: { width: 29, height: 29, borderRadius: 8, backgroundColor: 'rgba(255,251,221,0.36)', justifyContent: 'center', alignItems: 'center' },
    logCopy: { flex: 1 },
    logTitle: { color: c.actionInk, fontFamily: bold, fontSize: 11, letterSpacing: 0.8 },
    logHint: { color: c.actionInk, fontFamily: medium, fontSize: 8 },
    body: { color: c.secondary, fontFamily: medium, fontSize: 12, lineHeight: 18 },
    panel: { marginTop: 10, padding: 13, borderRadius: 12, borderWidth: 1, borderColor: c.rule, backgroundColor: c.panel, gap: 10 },
    detailRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
    detailCopy: { flex: 1, gap: 3 },
    detailTitle: { color: c.paper, fontFamily: bold, fontSize: 12 },
    management: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 9, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: c.rule },
    link: { color: c.gold, fontFamily: bold, fontSize: 11 },
    nav: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: c.background, borderTopWidth: 1, borderTopColor: c.rule, flexDirection: 'row', paddingHorizontal: 13, paddingTop: 10 },
    navItem: { flex: 1, minHeight: 45, alignItems: 'center', gap: 4 },
    navText: { color: c.secondary, fontFamily: medium, fontSize: 9 },
    selectedNavText: { color: c.gold },
    activity: { marginTop: 8 },
    activityHeader: { minHeight: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    activityTitle: { color: c.paper, fontFamily: headline, fontSize: 8, letterSpacing: 1 },
    activityRow: { minHeight: 34, paddingVertical: 4, flexDirection: 'row', alignItems: 'center', gap: 8, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: c.rule },
    activityCopy: { flex: 1, gap: 2 },
    activityText: { color: c.paper, fontFamily: medium, fontSize: 10, lineHeight: 14 },
    activityName: { fontFamily: bold },
    activityVenue: { color: c.secondary, fontFamily: medium, fontSize: 8 },
    activityTime: { color: c.secondary, fontFamily: medium, fontSize: 7 },
    refresh: { minWidth: 32, minHeight: 28, alignItems: 'center', justifyContent: 'center' },
    viewAll: { minHeight: 32, justifyContent: 'center', alignSelf: 'flex-start' },
  });
}
