import { StyleSheet } from 'react-native';
import home from '@/constants/homeColors';

export function createWarsStyles(fontsLoaded: boolean) {
  const medium = fontsLoaded ? 'WarsDM_500' : 'Inter_500Medium';
  const bold = fontsLoaded ? 'WarsDM_700' : 'Inter_700Bold';
  const headline = fontsLoaded ? 'WarsSpace_600' : 'Inter_600SemiBold';
  return StyleSheet.create({
    scroll: { width: '100%' },
    content: { width: '100%', maxWidth: 430, alignSelf: 'center', paddingHorizontal: 19 },
    statusBar: { position: 'absolute', top: 11, left: 25, right: 24, height: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    statusTime: { color: home.text, fontFamily: bold, fontSize: 12 },
    statusIcons: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    header: { height: 45, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    brand: { flexDirection: 'row', alignItems: 'center', gap: 7 },
    crest: { width: 31, height: 37 },
    wordmark: { width: 122, height: 41 },
    create: { minHeight: 36, paddingHorizontal: 11, borderWidth: 1, borderColor: 'rgba(255,209,46,0.38)', borderRadius: 10, backgroundColor: 'rgba(255,209,46,0.06)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
    createText: { color: home.gold, fontFamily: bold, fontSize: 10, letterSpacing: 0.16 },
    heading: { marginTop: 6, minHeight: 38 },
    eyebrow: { color: home.gold, fontFamily: bold, fontSize: 9, letterSpacing: 1.58, marginBottom: 3 },
    title: { color: home.text, fontFamily: headline, fontSize: 19, lineHeight: 22, letterSpacing: -0.65 },
    tabs: { marginTop: 13, minHeight: 38, padding: 3, gap: 3, flexDirection: 'row', borderWidth: 1, borderColor: 'rgba(234,230,220,0.08)', borderRadius: 11, backgroundColor: 'rgba(255,255,255,0.035)' },
    tab: { flex: 1, minHeight: 30, paddingVertical: 5, borderRadius: 8, borderWidth: 1, borderColor: 'transparent', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 7 },
    selectedTab: { borderColor: 'rgba(255,209,46,0.15)', backgroundColor: 'rgba(255,209,46,0.10)' },
    tabText: { color: '#a5a9ae', fontFamily: bold, fontSize: 10, letterSpacing: 0.82 },
    selectedTabText: { color: home.text },
    count: { minWidth: 17, minHeight: 17, paddingHorizontal: 4, borderRadius: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.09)' },
    selectedCount: { backgroundColor: home.gold },
    countText: { color: '#bbb7aa', fontFamily: bold, fontSize: 9 },
    selectedCountText: { color: home.actionInk },
    section: { marginTop: 17, gap: 10 },
    sectionHeader: { marginHorizontal: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    sectionTitle: { color: '#ededea', fontFamily: headline, fontSize: 11, letterSpacing: 0.82 },
    sectionSide: { color: '#818994', fontFamily: medium, fontSize: 10 },
    card: { minHeight: 158, paddingTop: 14, paddingHorizontal: 13, paddingBottom: 11, borderWidth: 1, borderColor: 'rgba(223,222,211,0.10)', borderRadius: 13, overflow: 'hidden', backgroundColor: '#0e131a' },
    compactCard: { minHeight: 130, paddingTop: 11, paddingBottom: 9 },
    completedCard: { minHeight: 90, paddingTop: 10, paddingBottom: 10 },
    photo: { position: 'absolute', top: 0, right: 0, bottom: 0, width: '49%', height: '100%', opacity: 0.88 },
    cardContent: { flex: 1, width: '73%', zIndex: 1 },
    badge: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    liveDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: home.gold },
    badgeText: { color: '#f3dc89', fontFamily: bold, fontSize: 8, lineHeight: 10, letterSpacing: 0.9 },
    cardTitle: { marginTop: 8, color: '#faf8f1', fontFamily: headline, fontSize: 21, lineHeight: 24, letterSpacing: -0.62 },
    compactTitle: { marginTop: 5, fontSize: 19, lineHeight: 22 },
    completedTitle: { marginTop: 5, fontSize: 17, lineHeight: 20 },
    metadata: { marginTop: 7, color: '#c5c6c7', fontFamily: medium, fontSize: 10, lineHeight: 13 },
    compactMetadata: { marginTop: 5 },
    separator: { color: home.gold },
    roster: { marginTop: 'auto', paddingTop: 7, paddingBottom: 6, flexDirection: 'row', alignItems: 'center' },
    compactRoster: { paddingTop: 4, paddingBottom: 4 },
    avatar: { width: 21, height: 21, marginLeft: -4, borderWidth: 1.5, borderColor: '#11151a', borderRadius: 11, overflow: 'hidden', backgroundColor: '#424f4f', alignItems: 'center', justifyContent: 'center' },
    firstAvatar: { marginLeft: 0, backgroundColor: '#f0c24d' },
    thirdAvatar: { backgroundColor: '#494f61' },
    moreAvatar: { backgroundColor: '#293039' },
    avatarImage: { width: '100%', height: '100%' },
    avatarText: { color: '#f4edda', fontFamily: bold, fontSize: 7, letterSpacing: -0.3 },
    firstAvatarText: { color: '#241d0b' },
    rosterText: { flex: 1, marginLeft: 7, color: '#d1d1cb', fontFamily: medium, fontSize: 8, lineHeight: 12 },
    footer: { paddingTop: 6, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: 'rgba(246,242,225,0.13)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 7 },
    completedFooter: { paddingTop: 4, borderTopWidth: 0 },
    rank: { flex: 1, color: '#aeb1b3', fontFamily: medium, fontSize: 9, lineHeight: 13 },
    rankValue: { color: '#f5ebc4', fontFamily: bold },
    score: { color: home.gold, fontFamily: bold, fontSize: 10 },
    chevron: { position: 'absolute', zIndex: 1, top: 11, right: 11, width: 25, height: 25, borderRadius: 13, borderWidth: 1, borderColor: 'rgba(255,255,255,0.19)', backgroundColor: 'rgba(4,7,11,0.25)', justifyContent: 'center', alignItems: 'center' },
    empty: { padding: 24, borderWidth: 1, borderColor: home.line, borderRadius: 13, backgroundColor: home.panel, alignItems: 'center', gap: 9 },
    emptyTitle: { color: home.text, fontFamily: headline, fontSize: 17, textAlign: 'center' },
    body: { color: home.muted, fontFamily: medium, fontSize: 12, lineHeight: 18 },
    centeredBody: { textAlign: 'center' },
    primaryButton: { minHeight: 40, marginTop: 7, paddingHorizontal: 14, borderRadius: 10, backgroundColor: home.gold, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 7 },
    primaryText: { color: home.actionInk, fontFamily: bold, fontSize: 12 },
    message: { marginTop: 17, padding: 13, borderWidth: 1, borderColor: home.line, borderRadius: 11, backgroundColor: home.panel, gap: 7 },
    retryText: { color: home.gold, fontFamily: bold, fontSize: 12 },
    retry: { alignSelf: 'flex-start', minHeight: 36, justifyContent: 'center', paddingRight: 12 },
    loading: { minHeight: 158, alignItems: 'center', justifyContent: 'center' },
    archiveLink: { alignSelf: 'flex-start', paddingVertical: 10 },
    legacyActions: { marginTop: 32, gap: 14 },
    join: { minHeight: 42, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: home.line, borderRadius: 11, backgroundColor: home.panel },
    joinText: { color: home.text, fontFamily: bold, fontSize: 12 },
  });
}

export type WarsStyles = ReturnType<typeof createWarsStyles>;
